import { StyleSheet } from "@react-pdf/renderer";
import { Fonts, Lab, Layout, Space, Type } from "../lab-theme";

export const s = StyleSheet.create({
  page: {
    backgroundColor: Lab.paper,
    paddingTop: Space.pageTop,
    paddingBottom: Space.pageBottom,
    paddingHorizontal: Space.pageX,
    fontFamily: Fonts.sans,
    color: Lab.ink,
  },
  mast: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: Space.mast,
    backgroundColor: Lab.navy,
    paddingHorizontal: Space.pageX,
    paddingTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  mastCopper: {
    position: "absolute",
    top: Space.mast,
    left: 0,
    right: 0,
    height: 1.1,
    backgroundColor: Lab.copper,
  },
  mastText: {
    color: Lab.ivory,
    fontSize: 7,
    fontFamily: Fonts.mono,
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  footer: {
    position: "absolute",
    bottom: 12,
    left: Space.pageX,
    right: Space.pageX,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 0.5,
    borderTopColor: Lab.hair,
    paddingTop: 5,
  },
  footerText: { ...Type.micro, letterSpacing: 0.5 },
  kicker: { ...Type.kicker, marginBottom: Space[3] },
  display: Type.display,
  title: Type.title,
  lead: Type.lead,
  ask: Type.ask,
  body: { ...Type.body, marginBottom: Space[2] },
  small: Type.small,
  label: { ...Type.label, marginBottom: Space[2] },
  data: Type.data,
  micro: Type.micro,
  rule: { height: 0.8, backgroundColor: Lab.copper, marginVertical: Space[4] },
  hair: { height: 0.45, backgroundColor: Lab.hair, marginVertical: Space[3] },
  step: { flexDirection: "row", gap: Space[2], marginBottom: Space[2], alignItems: "flex-start" },
  stepN: {
    width: 14,
    fontSize: 7.5,
    fontFamily: Fonts.mono,
    color: Lab.copper,
    marginTop: 1,
  },
  plate: {
    borderWidth: 0.6,
    borderColor: Lab.hair,
    padding: Space[3],
    flexGrow: 1,
  },
  plateName: { fontFamily: Fonts.serif, fontSize: 12, marginBottom: 3 },
  plateWhy: { fontSize: 8, lineHeight: 1.34, fontFamily: Fonts.sans },
  badge: {
    fontSize: 6.5,
    letterSpacing: 0.7,
    textTransform: "uppercase",
    fontFamily: Fonts.mono,
    paddingVertical: 1.5,
    paddingHorizontal: 4,
  },
  monthCard: {
    flexDirection: "row",
    borderWidth: 0.55,
    borderColor: Lab.hair,
    marginBottom: Space[3],
    backgroundColor: Lab.paper,
  },
  monthRail: {
    width: Layout.rail,
  },
  monthBody: {
    width: Layout.content - Layout.rail,
    paddingTop: Space[3],
    paddingRight: Space[3],
    paddingBottom: Space[3],
    paddingLeft: Space[3],
  },
  monthHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  monthName: { fontFamily: Fonts.serif, fontSize: 13, color: Lab.ink },
  feat: { flexDirection: "row", gap: 5, marginBottom: 3, alignItems: "flex-start" },
  featBar: { width: 1.8, height: 15, marginTop: 1.5 },
  featTitle: {
    fontSize: 7,
    fontFamily: Fonts.mono,
    letterSpacing: 0.7,
    textTransform: "uppercase",
    marginBottom: 1,
  },
  featLine: { fontSize: 8, color: Lab.slate, lineHeight: 1.32, fontFamily: Fonts.sans },
  restRow: { flexDirection: "row", flexWrap: "wrap", marginTop: 3 },
  restItem: {
    width: "50%",
    marginBottom: 2,
    paddingRight: 8,
    fontSize: 7,
    fontFamily: Fonts.mono,
    letterSpacing: 0.3,
    color: Lab.slate,
  },
  barTrack: { height: 3.2, backgroundColor: Lab.hair },
  barFill: { height: 3.2 },
  glanceCell: {
    width: Layout.col3,
    flexDirection: "row",
    borderWidth: 0.55,
    borderColor: Lab.hair,
    backgroundColor: Lab.paper,
  },
  glanceRail: {
    width: Layout.rail,
  },
  glanceBody: {
    width: Layout.col3 - Layout.rail,
    paddingTop: Space[2],
    paddingRight: Space[2],
    paddingBottom: Space[2],
    paddingLeft: Space[2],
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.45,
    borderBottomColor: Lab.hair,
    paddingVertical: 4.5,
    alignItems: "flex-start",
  },
  tableHead: {
    flexDirection: "row",
    borderBottomWidth: 0.9,
    borderBottomColor: Lab.copper,
    paddingBottom: 4,
    marginBottom: 1,
  },
  tableHeadText: {
    fontSize: 7,
    fontFamily: Fonts.mono,
    color: Lab.copper,
    letterSpacing: 1.1,
  },
  practice: {
    flexDirection: "row",
    borderWidth: 0.6,
    borderColor: Lab.copper,
    backgroundColor: Lab.wash,
  },
  practiceRail: {
    width: Layout.rail,
    backgroundColor: Lab.copper,
  },
  practiceBody: {
    width: Layout.content - Layout.rail,
    paddingVertical: Space[3],
    paddingHorizontal: Space[3],
  },
  zoneRow: { flexDirection: "row", marginBottom: 1.5 },
  zoneN: { width: 16, fontSize: 6.5, fontFamily: Fonts.mono, color: Lab.copper },
  zoneL: { fontSize: 7, fontFamily: Fonts.sans, color: Lab.slate },
  ribbon: { flexDirection: "row", marginBottom: Space[3], height: 18 },
  ribbonCell: {
    flexGrow: 1,
    flexShrink: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRightWidth: 0.4,
    borderRightColor: Lab.paper,
  },
  colophon: {
    marginTop: Space[5],
    paddingTop: Space[3],
    borderTopWidth: 0.8,
    borderTopColor: Lab.copper,
  },
  logRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 0.4,
    borderBottomColor: Lab.hair,
    paddingVertical: 4.2,
  },
  logBox: {
    width: 8,
    height: 8,
    borderWidth: 0.7,
    borderColor: Lab.copper,
    marginRight: 8,
  },
  logMonth: {
    width: 32,
    fontFamily: Fonts.mono,
    fontSize: 7.5,
    letterSpacing: 0.6,
    color: Lab.ink,
  },
  logClimate: {
    width: 62,
    fontFamily: Fonts.mono,
    fontSize: 7,
  },
  logAction: {
    width: Layout.content - 32 - 62 - 16,
    fontSize: 8.5,
    fontFamily: Fonts.sans,
    color: Lab.ink,
  },
  keyCard: {
    width: Layout.col3,
    borderWidth: 0.55,
    borderColor: Lab.hair,
    padding: Space[3],
  },
  plateFixed: {
    width: Layout.col3,
    flexGrow: 0,
  },
});
